jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    uses: apache/logging-parent/.github/workflows/build-reusable.yaml@fix/macos-java-8
    with:
      java-version: '8

        17

        '
      site-enabled: true
  deploy-release:
    if: github.repository == 'apache/logging-log4j2' && startsWith(github.ref_name,
      'release/2')
    needs: build
    permissions:
      contents: write
    secrets:
      GPG_SECRET_KEY: ${{ secrets.LOGGING_GPG_SECRET_KEY }}
      NEXUS_PASSWORD: ${{ secrets.LOGGING_STAGE_DEPLOYER_PW }}
      NEXUS_USERNAME: ${{ secrets.LOGGING_STAGE_DEPLOYER_USER }}
      SVN_PASSWORD: ${{ secrets.LOGGING_SVN_DEV_PASSWORD }}
      SVN_USERNAME: ${{ secrets.LOGGING_SVN_DEV_USERNAME }}
    uses: apache/logging-parent/.github/workflows/deploy-release-reusable.yaml@rel/11.1.0
    with:
      java-version: '8

        17

        '
      project-id: log4j
  deploy-snapshot:
    if: github.repository == 'apache/logging-log4j2' && github.ref_name == '2.x'
    needs: build
    secrets:
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PW }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USER }}
    uses: apache/logging-parent/.github/workflows/deploy-snapshot-reusable.yaml@rel/11.1.0
    with:
      java-version: '8

        17

        '
name: build
on:
  repository_dispatch:
    types: trigger-ga___build.yaml
permissions: read-all
