jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e
      with:
        days-before-close: 7
        days-before-stale: 60
        only-labels: waiting-for-user
        stale-issue-message: 'This issue is stale because it has been waiting for
          your feedback for more than 60 days. The Apache Logging Services community
          values every submitted issue, but without additional information from you,
          we are unable to provide a solution to your problem.

          Please comment on this issue or it will be closed in 7 days.

          '
name: Close stale issues
on:
  repository_dispatch:
    types: trigger-ga___close-stale.yaml
permissions:
  issues: write
