jobs:
  deploy-site-pro:
    if: github.repository == 'apache/logging-log4j2' && github.ref_name == '2.x-site-pro'
    permissions:
      contents: write
    secrets:
      GPG_SECRET_KEY: ${{ secrets.LOGGING_GPG_SECRET_KEY }}
    uses: apache/logging-parent/.github/workflows/deploy-site-reusable.yaml@rel/11.1.0
    with:
      asf-yaml-content: "publish:\n  profile: ~\n  whoami: ${{ github.ref_name }}-out\n\
        \  subdir: content/log4j/2.x\n"
      install-required: true
      target-branch: ${{ github.ref_name }}-out
  deploy-site-rel:
    needs: export-version
    permissions:
      contents: write
    secrets:
      GPG_SECRET_KEY: ${{ secrets.LOGGING_GPG_SECRET_KEY }}
    uses: apache/logging-parent/.github/workflows/deploy-site-reusable.yaml@rel/11.1.0
    with:
      asf-yaml-content: "staging:\n  profile: ~\n  whoami: ${{ github.ref_name }}-site-stg-out\n\
        \  subdir: content/log4j/${{ needs.export-version.outputs.version }}\n"
      install-required: true
      target-branch: ${{ github.ref_name }}-site-stg-out
  deploy-site-stg:
    if: github.repository == 'apache/logging-log4j2' && github.ref_name == '2.x'
    permissions:
      contents: write
    secrets:
      GPG_SECRET_KEY: ${{ secrets.LOGGING_GPG_SECRET_KEY }}
    uses: apache/logging-parent/.github/workflows/deploy-site-reusable.yaml@rel/11.1.0
    with:
      asf-yaml-content: "staging:\n  profile: ~\n  whoami: ${{ github.ref_name }}-site-stg-out\n\
        \  subdir: content/log4j/2.x\n"
      install-required: true
      target-branch: ${{ github.ref_name }}-site-stg-out
  export-version:
    if: github.repository == 'apache/logging-log4j2' && startsWith(github.ref_name,
      'release/2')
    outputs:
      version: ${{ steps.export-version.outputs.version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: export-version
      name: Export version
      run: 'version=$(echo "${{ github.ref_name }}" | sed ''s/^release\///'')

        echo "version=$version" >> "$GITHUB_OUTPUT"

        '
name: deploy-site
on:
  repository_dispatch:
    types: trigger-ga___deploy-site.yaml
permissions: read-all
