env:
  comment_user_type: "${{\n  github.event_type == 'issue_comment' &&\n  (\n    contains(fromJSON('[\"\
    COLLABORATOR\",\"MEMBER\",\"OWNER\"]'), github.event.comment.author_association)\
    \ && 'maintainer' || 'user'\n  ) || null\n}}"
  issue_user_type: "${{\n  contains(fromJSON('[\"COLLABORATOR\",\"MEMBER\",\"OWNER\"\
    ]'), github.event.issue.author_association) && 'maintainer' || 'user'\n}}"
jobs:
  check-labels:
    if: ${{ ! github.event.issue.pull_request }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        COMMENT_USER_TYPE: ${{ env.comment_user_type }}
        ISSUE_USER_TYPE: ${{ env.issue_user_type }}
      name: Print user type
      run: 'echo "Issue created by: " $ISSUE_USER_TYPE

        echo "Comment created by:" $COMMENT_USER_TYPE

        '
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ github.token }}
        ISSUE: ${{ github.event.issue.html_url }}
      if: github.event_type == 'issues' && env.issue_user_type == 'user' || env.comment_user_type
        == 'user'
      name: Add `waiting-for-maintainer` label
      run: 'gh issue edit $ISSUE --add-label ''waiting-for-maintainer'' --remove-label
        ''waiting-for-user''

        '
name: Check labels
on:
  repository_dispatch:
    types: trigger-ga___labeler.yaml
permissions:
  issues: write
