jobs:
  build:
    if: github.repository == 'apache/logging-log4j2' && github.event_name == 'pull_request_target'
      && github.actor == 'dependabot[bot]'
    uses: apache/logging-parent/.github/workflows/build-reusable.yaml@fix/macos-java-8
    with:
      java-version: '8

        17

        '
  merge-dependabot:
    needs: build
    permissions:
      contents: write
      pull-requests: write
    secrets:
      GPG_SECRET_KEY: ${{ secrets.LOGGING_GPG_SECRET_KEY }}
    uses: apache/logging-parent/.github/workflows/merge-dependabot-reusable.yaml@rel/11.1.0
    with:
      java-version: 17
name: merge-dependabot
on:
  repository_dispatch:
    types: trigger-ga___merge-dependabot.yaml
permissions: read-all
